shutterbug/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='home'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('dashboard/update', views.updateSessionDate, name='updateSessionDate'),
    path('dashboard/remove', views.deleteSession, name='deleteSession'),
    path('logout', views.userLogout, name='logout'),
    path('about', views.about, name='about'),
    path('login', views.userlogin, name='login'),
    path('signup', views.signup, name='signup')
]

shutterbug/search/urls.py
from django.urls import path, include
from . import views

app_name = 'search'

urlpatterns = [
    path('', views.searchPhotographers, name='search'),
    path('/book', views.book, name='book')
]

shutterbug/shutterbug/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('search', include('search.urls'))
]

shutterbug/search/models.py
from django.db import models
# Create your models here.

shutterbug/search/views.py
from django.shortcuts import redirect, render
from django.http import JsonResponse
from backend.models import Photographer, Client, PhotoshootSession
from django.contrib.auth.models import User
import uuid

# Create your views here.


def searchPhotographers(request):
    if request.user.is_authenticated:
        # check if request has parameters
        if(not (request.GET.get('base_price') and request.GET.get('city'))):
            if (request.GET.get('base_price')):  # if only base price is given
                price = request.GET.get('base_price')
                photographer_list = Photographer.objects.filter(
                    base_price__lte=price)

                if(len(photographer_list) == 0):
                    errString = 'No photographers with base price $' + \
                        request.GET.get('base_price')
                    context = {'error_message': errString}
                    return render(request, 'search.html', context)
                else:
                    context = {'success_message': 'list retreived',
                               'list': photographer_list}
                    return render(request, 'search.html', context)
            if (request.GET.get('city')):  # if only city is given
                search_city = request.GET.get('city')
                photographer_list = Photographer.objects.filter(
                    city=search_city)
                if(len(photographer_list) == 0):
                    errString = 'No photographers in city: ' + \
                        request.GET.get('city')
                    context = {'error_message': errString}
                    return render(request, 'search.html', context)
                else:
                    context = {'list': photographer_list,
                               'success_message': 'list retreived'}
                    return render(request, 'search.html', context)
        else:  # if both base price and city is given
            price = request.GET.get('base_price')
            search_city = request.GET.get('city')
            photographer_list = Photographer.objects.filter(
                base_price__lte=price, city=search_city)
            if(len(photographer_list) == 0):
                errString = 'No photographers with city ' + \
                    request.GET.get('city') + ' and base price $' + \
                    request.GET.get('base_price')
                context = {'error_message': errString}
                return render(request, 'search.html', context)
            else:
                context = {'list': photographer_list,
                           'success_message': 'list retreived'}
                return render(request, 'search.html', context)

        if request.is_ajax():  # ajax request handler for getting photographer details
            data = list(Photographer.objects.filter(
                id=request.GET.get('id')).values('first_name', 'last_name', 'city', 'address1', 'address2', 'base_price', 'telephone', 'email'))
            return JsonResponse(data, safe=False)

        return render(request, 'search.html')
    else:
        return render(request, 'login.html', {'err_message': 'Login to view dashboard or search'})


def book(request):
    p = Photographer.objects.get(email=request.POST.get('photographerEmail'))
    c = Client.objects.get(email=request.user.email)
    sessionID = uuid.uuid4()
    sessionDate = request.POST.get('sessionDate')
    try:
        PhotoshootSession.objects.get(client=c, session_date=sessionDate)
    except PhotoshootSession.DoesNotExist:
        PhotoshootSession.objects.create(
            session_id=sessionID, photographer=p, client=c, session_date=sessionDate)
        return redirect('/dashboard')
    return render(request, 'search.html', {'error_message': 'You already have an appointment on this date'})

shutterbug/templates/about.html
<!DOCTYPE html>
<html>
<head>
    <title>Shutterbug-About</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles/index.css' %}"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    
</head>
<body>
  <nav class="py-2 primary-background border-bottom">
    <div class="container d-flex flex-wrap">
      <ul class="nav me-auto">
        <li class="nav-item"><a href="{% url 'home:home'%}" class="nav-link link-dark px-2">Home</a></li>
        <li class="nav-item"><a href="{% url 'home:about'%}" class="nav-link link-dark px-2 active" aria-current="page">About</a></li>
        <li class="nav-item"><a href="{% url 'home:dashboard'%}" class="nav-link link-dark px-2">Dashboard</a></li>
        <li class="nav-item"><a href="{% url 'search:search'%}" class="nav-link link-dark px-2">Search Photographers</a></li>
      </ul>
      <ul class="nav">
        <li class="nav-item"><a href="{% url 'home:login'%}" class="nav-link link-dark px-2">Login</a></li>
        <li class="nav-item"><a href="{% url 'home:logout'%}" class="nav-link link-dark px-2">Logout</a></li>
        <li class="nav-item"><a href="{% url 'home:signup'%}" class="nav-link link-dark px-2">Sign up</a></li>
      </ul>
    </div>
  </nav>
  <header class="pt-3 pb-2 border-bottom">
    <div class="container d-flex flex-wrap justify-content-start">
      <a href="{% url 'home:home'%}" class="align-items-center mb-lg-0 me-lg-auto text-dark text-decoration-none">
        <span class="fs-4">{% load static %}<img src="{% static 'images/logo.png' %}" class="img-fluid" width="200px" alt='shutterbug logo'/></span>
      </a>
    </div>
  </header>
  <div class="container my-4 text-center">
    <h2 class="display-4">A wedding photographer search platform.</h2>
    <p class="lead fs-3">Shutterbug is a wedding photographer search platform that will allow users to search for photographers within their preferred city.</p>
    <p class="lead fs-3">You must signup if you are a new user or login to use the search feature.</p>
    <p class="lead fs-3"><span class="mark">For Photographers</span> - You can register yourselves through the signup page to be seen by potential clients.</p>
  </div>
  <div class="container d-flex p-2 flex-column flex-lg-row justify-content-between mb-4">
    <div class="card flex-fill">
        <iframe width="560" height="400" src="https://www.youtube.com/embed/dSNzx3pVWLg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen class="card-img-top"></iframe>
    </div>
    <div class="card about-card">
        <div class="card-body">
            <h5 class="card-title">Why Shutterbug?</h5>
            <p class="card-text">By using Shutterbug, you get useful benefits.</p>
            <div class="accordion" id="accordionExample">
                <div class="accordion-item">
                  <h2 class="accordion-header" id="headingOne">
                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                      <strong>No Ads!</strong>
                    </button>
                  </h2>
                  <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                    <div class="accordion-body text-wrap">
                      There is no Ads on this platform. Use the application without the problems of targeted advertisements.
                    </div>
                  </div>
                </div>
                <div class="accordion-item">
                  <h2 class="accordion-header" id="headingTwo">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                      <strong>Low cost photographers</strong>
                    </button>
                  </h2>
                  <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                    <div class="accordion-body text-wrap">
                      The cost of hiring photographers will be greatly reduced. You can find cheap photographers for hire.
                    </div>
                  </div>
                </div>
                <div class="accordion-item">
                  <h2 class="accordion-header" id="headingThree">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                      <strong>Quick Search!</strong>
                    </button>
                  </h2>
                  <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                    <div class="accordion-body text-wrap">
                      Find and browse through photographers at a faster pace.
                    </div>
                  </div>
                </div>
              </div>
          </div>
    </div>
  </div>
  <footer class="bg-light text-center text-lg-start">
    <div class="text-center p-3 primary-background">
        © 2020 Copyright:
        <a class="text-dark" href="{% url 'home:home'%}">Shutterbug.com</a>
      </div>
  </footer>
  </body>
  </html>

shutterbug/templates/dashboard.html
<!DOCTYPE html>
<html>
<head>
    <title>Shutterbug-Dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles/index.css' %}"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    {% load static %}
    <script src="{% static 'scripts/dash.js' %}"></script>
    
</head>
<body>
  <nav class="py-2 primary-background border-bottom">
    <div class="container d-flex flex-wrap">
      <ul class="nav me-auto">
        <li class="nav-item"><a href="{% url 'home:home'%}" class="nav-link link-dark px-2 active" aria-current="page">Home</a></li>
        <li class="nav-item"><a href="{% url 'home:about'%}" class="nav-link link-dark px-2">About</a></li>
        <li class="nav-item"><a href="{% url 'home:dashboard'%}" class="nav-link link-dark px-2">Dashboard</a></li>
        <li class="nav-item"><a href="{% url 'search:search'%}" class="nav-link link-dark px-2">Search Photographers</a></li>
      </ul>
      <ul class="nav">
        <li class="nav-item"><a href="{% url 'home:login'%}" class="nav-link link-dark px-2">Login</a></li>
        <li class="nav-item"><a href="{% url 'home:logout'%}" class="nav-link link-dark px-2">Logout</a></li>
        <li class="nav-item"><a href="{% url 'home:signup'%}" class="nav-link link-dark px-2">Sign up</a></li>
      </ul>
    </div>
  </nav>
  <header class="pt-3 pb-2 border-bottom">
    <div class="container d-flex flex-wrap justify-content-start">
      <a href="{% url 'home:home'%}" class="align-items-center mb-lg-0 me-lg-auto text-dark text-decoration-none">
        <span class="fs-4">
          {% load static %}
          <img src="{% static 'images/logo.png' %}" class="img-fluid" width="200px" alt='shutterbug logo'/>
        </span>
      </a>
    </div>
  </header>
  <div class="container my-4">
    <h2 class="display-4 text-center">Hello {{ Firstname }}</h2>
    <p class="lead fs-3">Your Upcoming Sessions:</p>
  </div>
  <!--Dash section-->
  <div class="container">
    <div class="row">
        <div class="col-lg-6">
            <ol class="list-group list-group-numbered">
                {% for shoot in list %}
                <li class="list-group-item d-flex justify-content-between align-items-start">
                  <div class="ms-2 me-auto">
                    <div class="fw-bold">{{ shoot.photographer.first_name }}</div>
                    Date: {{ shoot.session_date }}
                    <div class="d-grid gap-2 d-md-block mt-3">
                        <button class="btn btn-primary" type="button">Reschedule</button>
                        <form method="POST" action="/dashboard/remove" class="mt-3">{% csrf_token %}
                          <input type="text" value="{{ shoot.session_id }}" name="sessionId" hidden>
                          <button class="btn btn-danger" type="button">Cancel</button>
                          <p class="alert alert-danger mt-3 d-none">
                            <strong>Are you sure?</strong>
                            <button class="btn btn-secondary" type="submit">YES</button>
                          </p>
                        </form>
                    </div>
                    <form method="POST" class="d-none" action="/dashboard/update">
                        {% csrf_token %}
                        New date:
                        <input class="form-control my-3" type="date" id="newDate" name="newDate">
                        <button type="submit" class="btn btn-warning btn-small">Update</button>
                        <input type="text" value="{{ shoot.session_id }}" name="sessionId" hidden>
                    </form>
                  </div>
                  
                </li>
                {% endfor %}
              </ol>
              {% if err_message %}
                <p class="alert alert-danger mt-3">
                <strong>{{ err_message }}</strong>
                </p>
              {% endif %}
        </div>
    </div>
  </div>

shutterbug/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Shutterbug-Home</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles/index.css' %}"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    {% load static %}
    <script src="{% static 'scripts/index.js' %}"></script>
    
</head>
<body>
  <nav class="py-2 primary-background border-bottom">
    <div class="container d-flex flex-wrap">
      <ul class="nav me-auto">
        <li class="nav-item"><a href="{% url 'home:home'%}" class="nav-link link-dark px-2 active" aria-current="page">Home</a></li>
        <li class="nav-item"><a href="{% url 'home:about'%}" class="nav-link link-dark px-2">About</a></li>
        <li class="nav-item"><a href="{% url 'home:dashboard'%}" class="nav-link link-dark px-2">Dashboard</a></li>
        <li class="nav-item"><a href="{% url 'search:search'%}" class="nav-link link-dark px-2">Search Photographers</a></li>
      </ul>
      <ul class="nav">
        <li class="nav-item"><a href="{% url 'home:login'%}" class="nav-link link-dark px-2">Login</a></li>
        <li class="nav-item"><a href="{% url 'home:logout'%}" class="nav-link link-dark px-2">Logout</a></li>
        <li class="nav-item"><a href="{% url 'home:signup'%}" class="nav-link link-dark px-2">Sign up</a></li>
      </ul>
    </div>
  </nav>
  <header class="pt-3 pb-2 border-bottom">
    <div class="container d-flex flex-wrap justify-content-start">
      <a href="{% url 'home:home'%}" class="align-items-center mb-lg-0 me-lg-auto text-dark text-decoration-none">
        <span class="fs-4">
          {% load static %}
          <img src="{% static 'images/logo.png' %}" class="img-fluid" width="200px" alt='shutterbug logo'/>
        </span>
      </a>
    </div>
  </header>
  <div class="container my-4">
    <h2 class="display-3 text-center">Welcome to Shutterbug</h2>
    <h4 class="text-center text-muted">Find Your Photographer</h4>
  </div>
  <!--image slider-->
  <div class="container">
    <div class="slider-outer">
      <span class="prev"><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
        <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
      </svg></span>
      <div class="slider-inner">
        {% load static %}
        <img src="{% static 'images/carousel-1.jpg' %}" class="active"/>
        {% load static %}
        <img src="{% static 'images/carousel-2.jpg' %}" />
        {% load static %}
        <img src="{% static 'images/carousel-3.jpg' %}"/>
      </div>
      <span class="next"><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
        <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
      </svg></span>
    </div>
  </div>
  <div class="container">
    <p class="lead text-center fs-3">
      Use Shutterbug to find and connect with photographers near you.
    </p>
    <p class="lead text-center fs-3">
      Login or Sign Up to start your search.
    </p>
  </div>
  <!--footer-->
  <footer class="bg-light text-center text-lg-start">
    <div class="container p-4">
      <div class="row">
        <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
          <h5 class="text-uppercase">For Photographers</h5>
          <p>
            Sign Up to register yourselves and be seen to many potential Clients.
          </p>
        </div>
        <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
          <h5 class="text-uppercase">For Clients</h5>
          <p>
            Sign up to start searching and contacting Photographers.
          </p>
        </div>
      </div>
    </div>
    <div class="text-center p-3 primary-background">
      © 2020 Copyright:
      <a class="text-dark" href="{% url 'home:home'%}">Shutterbug.com</a>
    </div>

  </footer>  
</body>
</html>

shutterbug/templates/search.html
<!DOCTYPE html>
<html>
<head>
    <title>Shutterbug-Search</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles/index.css' %}"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    {% load static %}
    <script src="{% static 'scripts/search.js' %}"></script>
    
</head>
<body>
  <nav class="py-2 primary-background border-bottom">
    <div class="container d-flex flex-wrap">
      <ul class="nav me-auto">
        <li class="nav-item"><a href="{% url 'home:home'%}" class="nav-link link-dark px-2">Home</a></li>
        <li class="nav-item"><a href="{% url 'home:about'%}" class="nav-link link-dark px-2">About</a></li>
        <li class="nav-item"><a href="{% url 'home:dashboard'%}" class="nav-link link-dark px-2">Dashboard</a></li>
        <li class="nav-item"><a href="{% url 'search:search'%}" class="nav-link link-dark px-2 active"  aria-current="page">Search Photographers</a></li>
      </ul>
      <ul class="nav">
        <li class="nav-item"><a href="{% url 'home:login'%}" class="nav-link link-dark px-2">Login</a></li>
        <li class="nav-item"><a href="{% url 'home:logout'%}" class="nav-link link-dark px-2">Logout</a></li>
        <li class="nav-item"><a href="{% url 'home:signup'%}" class="nav-link link-dark px-2">Sign up</a></li>
      </ul>
    </div>
  </nav>
  <header class="pt-3 pb-2 border-bottom">
    <div class="container d-flex flex-wrap justify-content-start">
      <a href="{% url 'home:home'%}" class="align-items-center mb-lg-0 me-lg-auto text-dark text-decoration-none">
        <span class="fs-4">{% load static %}<img src="{% static 'images/logo.png' %}" class="img-fluid" width="200px" alt='shutterbug logo'/></span>
      </a>
    </div>
  </header>
  <!--search form-->
  
  
  <div class="container my-4">
      <h2 class="display-5 text-center">Search For Photographers</h2>
      <p class="lead fs-4">Enter either City or Base Price:</p>
      <form class="my-3" action="/search" method="GET" id="searchForm">
              <div class="row mb-3">
                <label for="city" class="col-form-label col-sm-2 text-center text-sm-end">City:</label>
                <div class="col-sm-4">
                <input type="text" id="city" name="city" class="form-control">
                </div>
              </div>
              <div class="row mb-3">
                <label for="city" class="col-form-label col-sm-2 text-center text-sm-end">Base Price:</label>
                <div class="col-sm-4">
                    <div class="input-group">
                        <span class="input-group-text">$</span>
                        <input type="number" id="baseprice" name="base_price" class="form-control col-3">
                    </div>
                </div>
              </div>
              <div class="row">
                  <div class="col-sm-12 text-center">
                    <button type="submit" class="btn btn-lg primary-background me-2" id="searchButton" disabled>Search</button>
                    <button type="reset" class="btn btn-lg primary-background" id="resetButton">Reset</button>
                  </div>
              </div>
      </form>
  </div>
  <!--results container-->
  {% if error_message %}
        <p class="alert alert-danger">
	    <strong>{{ error_message }}</strong>
        </p>
  {% endif %}
  {% if success_message %}
  <div class="container my-4" id="results">
    <h5 class="display-6 mb-3">Results:</h5>
    <div class="row">
        <div class="col-lg-5">
            <div class="list-group" id='resultsList'>
                {% for photographer in list %}
                  <button type="button" class="list-group-item list-group-item-action" value="{{ photographer.id }}">
                    <strong class="fs-5">{{ photographer.first_name }}</strong>
                    <p>City: {{ photographer.city }} &nbsp;&nbsp;Base Price: ${{ photographer.base_price }}</p>
                  </button>
                {% endfor %}
              </div>
        </div>
        <div class="col-lg-7 mt-2 mt-lg-0">
            <div class="card d-none"  id='profileCard'>
                <strong class="fs-5 card-header" id='cardName'>Photographer Name 1</strong>
                <div class="card-body">
                {% load static %}
                <img src="{% static 'images/blank.png' %}" class="card-img-top" width="100%" height="200" alt="profile picture">
                  <h6 class="card-title mt-3">City: <span id="cardCity"></span></h6>
                  <h6 class="card-title">Address: <span id="cardAddress"></span></h6>
                  <h6 class="card-title">Base Price: $<span  id="cardBasePrice"></span></h6>                  
                  <h6 class="card-title">Phone: <a href="tel:100-1231234" class="card-link"  id="cardPhone">100-1231234</a></h6>
                  <h6 class="card-title">Email: <a href="mailto:xxx@yyy.com" class="card-link" id="cardEmail">xxx@yyy.com</a></h6>
                  <h6 class="card-title">Select session date:</h6>
                  <form method="POST" id="bookingForm" action="{% url 'search:book' %}">{% csrf_token %}
                    <input class="form-control my-3" type="date" id="sessionDate" name="sessionDate">
                    <input type="email" name="photographerEmail" id="photographerEmail" hidden>
                    <button type="submit" class="btn primary-background" id="bookButton">Book</button>
                  </form>
                </div>
              </div>
        </div>
    </div>
  </div>
  {% endif %}
  <!--footer-->
  <footer class="bg-light text-center text-lg-start">
    <div class="text-center p-3 primary-background">
        © 2020 Copyright:
        <a class="text-dark" href="{% url 'home:home'%}">Shutterbug.com</a>
      </div>
  </footer>
  </body>
  </html>